import random



#build a demo class that has a method that returns a random number between 0 and 100

class DemoClassOne:
    def __init__(self):
        self.random_number = random.randint(0, 100)

    def get_random_string(self):
        return self.random_number

    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: create a function that prints a grumpy message
    # 🕒 Timestamp: 2025-06-18 09:30:16
    ################################################################################
    def grumpy_message(self):
        print("I'm not in a good mood today!")
    
    def nice_day(self):
        print("Have a nice day")

    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: create a function to print some emojis in the console
    # 🕒 Timestamp: 2025-06-18 09:42:46
    ################################################################################

    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: change the print_emojis function to print 3 emojis
    # 🕒 Timestamp: 2025-06-18 10:41:54
    ################################################################################
    
    def print_emojis():
        print("😀 😀 😀")

    def print_oakley():
        print('oakley')
       

    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: write a funciton that prints "welcome"
    # 🕒 Timestamp: 2025-06-18 10:18:48
    ################################################################################
    
    def print_welcome():
        print("welcome")



    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: create a function that devides two numbers
    # 🕒 Timestamp: 2025-06-18 10:22:11
    ################################################################################
    
    def divide(num1, num2):
        return num1 / num2

    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: create a function that ads and subtracts depending on an arugment that's passed
    # 🕒 Timestamp: 2025-06-18 10:24:38
    ################################################################################
    
    def calculate(operation, num1, num2):
        if operation == 'add':
            return num1 + num2
        elif operation == 'subtract':
            return num1 - num2
        else:
            return "Invalid operation"


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: write a function called glasses that takes in the argument of a string and prints the glasses are {string}
    # 🕒 Timestamp: 2025-06-18 10:31:54
    ################################################################################
    
    def glasses(string):
        print(f"The glasses are {string}")


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: write a function that prints a string back out
    # 🕒 Timestamp: 2025-06-18 10:37:07
    ################################################################################
    
    def print_string(s):
        print(s)


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function called big that prints small
    # 🕒 Timestamp: 2025-06-18 10:39:22
    ################################################################################
    
    def big():
        print("small")


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a funcion that prints "title: coming soon"
    # 🕒 Timestamp: 2025-06-18 11:08:52
    ################################################################################
    
    def print_title():
        print("title: coming soon")


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: write a function that prints adios!
    # 🕒 Timestamp: 2025-06-18 11:11:59
    ################################################################################
    
    def print_adios():
        print("Adios!")


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: write a funciton that prints "cianara"
    # 🕒 Timestamp: 2025-06-18 11:14:14
    ################################################################################
    
    def print_cianara():
        print("cianara")


    
    


    
    ################################################################################
    # Generated by CodeClerk
    # Prompt: make a function that does anything simple
    # Timestamp: 2025-06-18 11:22:39
    ################################################################################
    
    def greet(name):
        return f"Hello, {name}!"


    
    ################################################################################
    # Generated by CodeClerk
    # Prompt: create a funciton to print hi
    # Timestamp: 2025-06-18 11:40:39
    ################################################################################
    
    def print_hi():
        print("hi")

class DemoClassTwo:
    def __init__(self):
        self.random_number = random.randint(0, 100)

    def get_random_number(self):
        return self.random_number

    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function that generates a number less than 4.
    # 🕒 Timestamp: 2025-06-17 17:28:16
    ################################################################################
    def generate_number(self):
        return random.uniform(0, 4)

    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: write a funciton tha prints 'rayban'
    # 🕒 Timestamp: 2025-06-18 10:17:53
    ################################################################################
    
    def print_brand():
        print('rayban')



    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function called big that prints small
    # 🕒 Timestamp: 2025-06-18 10:39:46
    ################################################################################
    

    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function called big that prints small and then prints big on a new line
    # 🕒 Timestamp: 2025-06-18 10:41:00
    ################################################################################
    
    def big():
        print("small")
        print("big")


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function called big that prints small and then prints big on a new line
    # 🕒 Timestamp: 2025-06-18 10:41:00
    ################################################################################
    
    def big():
        print("small")
        print("big")


    
    ################################################################################
    # Generated by CodeClerk
    # Prompt: make a function that does anything simple
    # Timestamp: 2025-06-18 11:22:59
    ################################################################################
    
    def greet(name):
        return f"Hello, {name}!"

# 🛠️  Generated by CodeClerk
# 📌 Prompt: make a function called big that prints small
# 🕒 Timestamp: 2025-06-18 10:40:09
################################################################################
def big():
    print("small")
