import random

def reverse_string(s):
    return s[::-1]

def reverse_string(s):
    return s[::-1]

################################################################################
# 🛠️  Generated by CodeClerk
# 📌 Prompt: write two python math functions, one for adding and one for subracting
# 🕒 Timestamp: 2025-06-17 16:35:13
################################################################################
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

print(add(5, 3))  # Outputs: 8
print(subtract(5, 3))  # Outputs: 2

################################################################################
# 🛠️  Generated by CodeClerk
# 📌 Prompt: write a function that doubles the input number
# 🕒 Timestamp: 2025-06-17 16:39:57
################################################################################
def double_number(num):
    return num * 2

print(double_number(5))  # Outputs: 10

################################################################################
# 🛠️  Generated by CodeClerk
# 📌 Prompt: create a function that prints a warm greeting when called, and one that makes an ugly message. They can be strings, no need to generate random messages.
# 🕒 Timestamp: 2025-06-17 16:50:56
################################################################################
def warm_greeting():
    print("Hello! Hope you're having a wonderful day!")

def ugly_message():
    print("You're as pleasant as an undercooked potato!")

warm_greeting()
ugly_message()

#build a demo class that has a method that returns a random number between 0 and 100

class DemoClass:
    def __init__(self):
        self.random_number = random.randint(0, 100)

    def get_random_string(self):
        return self.random_number


    
 





    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function prints "have a nice day"
    # 🕒 Timestamp: 2025-06-17 17:29:02
    ################################################################################
        def nice_day():
        print("Have a nice day")
    
    function niceDay() {
        console.log("Have a nice day");
    }

    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function prints "have a nice day"
    # 🕒 Timestamp: 2025-06-17 17:29:52
    ################################################################################
        def nice_day():
        print("have a nice day")
    
    function niceDay() {
        console.log("have a nice day");
    }
#build a class that has a method that returns a random number between 0 and 100

class RandomNumberGenerator:
    def __init__(self):
        self.random_number = random.randint(0, 100)

    def get_random_number(self):
        return self.random_number


    
    ################################################################################
    # 🛠️  Generated by CodeClerk
    # 📌 Prompt: make a function that generates a number less than 4.
    # 🕒 Timestamp: 2025-06-17 17:28:16
    ################################################################################
        import random
    
    def generate_number():
        return random.uniform(0, 4)
random_number_generator = RandomNumberGenerator()